version: '3.4'

services:
  E-Auction:
    image: mongo

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Services\ProductService\ProductApi\Dockerfile

  buyerbidservice.api:
    image: ${DOCKER_REGISTRY-}buyerbidserviceapi
    build:
      context: .
      dockerfile: Services/BuyerBidService/BuyerBidService.Api/Dockerfile
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
  rabbitmq:
    image: rabbitmq:3-management-alpine


  apigateways:
    image: ${DOCKER_REGISTRY-}apigateways
    build:
      context: .
      dockerfile: APIGateway/ApiGateways/Dockerfile

volumes:
  #mongo_data:
  elasticsearch-data:

